name: Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --non-interactive

      - name: Lint code
        run: yarn lint:scripts && yarn lint:styles

      - name: Build website
        run: yarn build

      - name: Wait for the Netlify Preview to finish
        uses: josephduffy/wait-for-netlify-action@v1
        id: netlify-preview
        with:
          site_name: 'gregoralbrecht'
          max_timeout: 500

      - name: Audit preview using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ steps.netlify-preview.outputs.url }}
          uploadArtifacts: true
          temporaryPublicStorage: true
